// <auto-generated />
using System;
using FishApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606140018_AddCodigoToPez")]
    partial class AddCodigoToPez
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishApp.API.Models.Estanque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Tipo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Estanque", (string)null);
                });

            modelBuilder.Entity("FishApp.API.Models.Pez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PeriodoReproduccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pez", (string)null);
                });

            modelBuilder.Entity("FishApp.API.Models.PezEstanque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstanque")
                        .HasColumnType("int");

                    b.Property<int>("IdPez")
                        .HasColumnType("int");

                    b.Property<string>("MotivoMovimento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstanque");

                    b.HasIndex("IdPez");

                    b.ToTable("PezEstanque", (string)null);
                });

            modelBuilder.Entity("FishApp.API.Models.PezEstanque", b =>
                {
                    b.HasOne("FishApp.API.Models.Estanque", "Estanque")
                        .WithMany("PecesEstanques")
                        .HasForeignKey("IdEstanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishApp.API.Models.Pez", "Pez")
                        .WithMany("PecesEstanques")
                        .HasForeignKey("IdPez")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estanque");

                    b.Navigation("Pez");
                });

            modelBuilder.Entity("FishApp.API.Models.Estanque", b =>
                {
                    b.Navigation("PecesEstanques");
                });

            modelBuilder.Entity("FishApp.API.Models.Pez", b =>
                {
                    b.Navigation("PecesEstanques");
                });
#pragma warning restore 612, 618
        }
    }
}
